/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include "atmel_start_pins.h"
#include "port.h"
#include <system.h>

/* Configure pins and initialize registers */
void ADC_0_initialization(void) {
#if USE_ADC
    ADC_0_init();
#endif
}

/* Configure pins and initialize registers */
void AC_0_initialization(void) {
#if USE_ADC
    AC_0_init();
#endif
}

/* configure pins and initialize registers */
void I2C_0_initialization(void) {
#if USE_I2C
    I2C_0_init();
#endif
}

/* configure the pins and initialize the registers */
void SPI_0_initialization(void) {
#if USE_SPI
    // Set pin direction to input
    PORT_set_pin_dir(SPI_MISO_PORT, SPI_MISO_PIN, PORT_DIR_IN);
    PORT_set_pin_pull_mode(SPI_MISO_PORT, SPI_MISO_PIN, PORT_PULL_OFF);
    // Set pin direction to output
    PORT_set_pin_dir(SPI_MOSI_PORT, SPI_MOSI_PIN, PORT_DIR_OUT);
    PORT_set_pin_level(SPI_MOSI_PORT, SPI_MOSI_PIN, false);
    // Set pin direction to output
    PORT_set_pin_dir(SPI_SCK_PORT, SPI_SCK_PIN, PORT_DIR_OUT);
    PORT_set_pin_level(SPI_SCK_PORT, SPI_SCK_PIN, false);

    SPI_0_init();
#endif
}

void PWM_0_initialization(void) {
#if USE_PWM
    PWM_0_init();
#endif
}

void TIMER_0_initialization(void) {
#if USE_TIMER
    TIMER_0_init();
#endif
}

/* configure pins and initialize registers */
void USART_0_initialization(void) {
#if USE_USART
    // Set pin direction to input
    PORT_set_pin_dir(USART_RX_PORT, USART_RX_PIN, PORT_DIR_IN);
    PORT_set_pin_pull_mode(USART_RX_PORT, USART_RX_PIN,
                           // <y> Pull configuration
                           // <id> pad_pull_config
                           // <PORT_PULL_OFF"> Off
                           // <PORT_PULL_UP"> Pull-up
                           PORT_PULL_OFF);

    // Set pin direction to output
    PORT_set_pin_dir(USART_TX_PORT, USART_TX_PIN, PORT_DIR_OUT);
    PORT_set_pin_level(USART_TX_PORT, USART_TX_PIN, false);
    USART_0_init();
#endif
}

/**
 * \brief System initialization
 */
void system_init() {
    /* Deinit all peripherals and disable all IO Banks.
     * What is needed will have to be turned on by application
     */
    mcu_init();
    /* Set up system clock */
    sysctrl_init();
    FLASH_0_init();
#if USE_WDT
    WDT_0_init();
#endif
    ADC_0_initialization();
    AC_0_initialization();
    I2C_0_initialization();
    SPI_0_initialization();
    PWM_0_initialization();
    TIMER_0_initialization();
    USART_0_initialization();
}
